version: '2'
services:
  web:
    build: ./web
    expose:
      - "5000"
    depends_on:
      - redis
  redis:
    image: redis
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
